######################################################################################################
#    _____ _                 _       _____                    _                         _
#   / ____(_)               | |     / ____|                  | |                       | |
#  | (___  _ _ __ ___  _ __ | | ___| (___   ___ ___  _ __ ___| |__   ___   __ _ _ __ __| |
#  \___ \| | '_ ` _ \| '_ \| |/ _ \\___ \ / __/ _ \| '__/ _ \ '_ \ / _ \ / _` | '__/ _` |
#  ____) | | | | | | | |_) | |  __/____) | (_| (_) | | |  __/ |_) | (_) | (_| | | | (_| |
# |_____/|_|_| |_| |_| .__/|_|\___|_____/ \___\___/|_|  \___|_.__/ \___/ \__,_|_|  \__,_|
#                          | |
#                          |_|
# by Haizon
# Version: 1.0.0
#
# This plugin is only compatible with the Plugin "PlaceholderAPI"
######################################################################################################

scoreboard:
  title: "&eYOURSERVER.NET"
  list:
  - "&1"
  - "&7TEST"
  - "&e123"
  - "&2"
  - "&7TES"
  - "&e123"
  - "&3"
  - "&7TE"
  - "&e1"
  - "&4"